package model

import scala.util.Try

enum Country(
    // ISO 3166-1 alpha 2 "short" code format
    val code: String,
    val name: String
) {
  case GI extends Country("GI", "Gibraltar")
  case HT extends Country("HT", "Haiti")
  case VG extends Country("VG", "British Virgin Islands")
  case GD extends Country("GD", "Grenada")
  case VU extends Country("VU", "Vanuatu")
  case SS extends Country("SS", "South Sudan")
  case IQ extends Country("IQ", "Iraq")
  case FM extends Country("FM", "Micronesia")
  case PL extends Country("PL", "Poland")
  case TL extends Country("TL", "East Timor")
  case SH extends Country("SH", "Saint Helena")
  case JO extends Country("JO", "Jordan")
  case GA extends Country("GA", "Gabon")
  case AX extends Country("AX", "Åland Islands")
  case ST extends Country("ST", "Sao Tome & Principe")
  case MS extends Country("MS", "Montserrat")
  case MQ extends Country("MQ", "Martinique")
  case UM extends Country("UM", "United States Minor Outlying Islands")
  case PH extends Country("PH", "Philippines")
  case SO extends Country("SO", "Somalia")
  case MG extends Country("MG", "Madagascar")
  case AD extends Country("AD", "Andorra")
  case FK extends Country("FK", "Falkland Islands")
  case DZ extends Country("DZ", "Algeria")
  case LI extends Country("LI", "Liechtenstein")
  case NF extends Country("NF", "Norfolk Island")
  case KI extends Country("KI", "Kiribati")
  case AO extends Country("AO", "Angola")
  case HR extends Country("HR", "Croatia")
  case LU extends Country("LU", "Luxembourg")
  case LB extends Country("LB", "Lebanon")
  case ER extends Country("ER", "Eritrea")
  case US extends Country("US", "United States")
  case GR extends Country("GR", "Greece")
  case BT extends Country("BT", "Bhutan")
  case BA extends Country("BA", "Bosnia-Herzegovina")
  case VE extends Country("VE", "Venezuela")
  case UZ extends Country("UZ", "Uzbekistan")
  case SY extends Country("SY", "Syria")
  case VC extends Country("VC", "Saint Vincent & The Grenadines")
  case DM extends Country("DM", "Dominica")
  case JP extends Country("JP", "Japan")
  case SJ extends Country("SJ", "Svalbard and Jan Mayen")
  case AF extends Country("AF", "Afghanistan")
  case WS extends Country("WS", "Samoa")
  case NE extends Country("NE", "Niger")
  case MP extends Country("MP", "Northern Mariana Islands")
  case VI extends Country("VI", "United States Virgin Islands")
  case BQ extends Country("BQ", "Bonaire, Saint Eustatius and Saba")
  case ES extends Country("ES", "Spain")
  case MC extends Country("MC", "Monaco")
  case JE extends Country("JE", "Jersey")
  case OM extends Country("OM", "Oman")
  case TH extends Country("TH", "Thailand")
  case RW extends Country("RW", "Rwanda")
  case NA extends Country("NA", "Namibia")
  case LA extends Country("LA", "Laos")
  case PN extends Country("PN", "Pitcairn Islands")
  case TG extends Country("TG", "Togo")
  case QA extends Country("QA", "Qatar")
  case AZ extends Country("AZ", "Azerbaijan")
  case RU extends Country("RU", "Russia")
  case PR extends Country("PR", "Puerto Rico")
  case KR extends Country("KR", "South Korea")
  case EE extends Country("EE", "Estonia")
  case KH extends Country("KH", "Cambodia")
  case AI extends Country("AI", "Anguilla")
  case RO extends Country("RO", "Romania")
  case YT extends Country("YT", "Mayotte")
  case CN extends Country("CN", "China")
  case NG extends Country("NG", "Nigeria")
  case DK extends Country("DK", "Denmark")
  case BE extends Country("BE", "Belgium")
  case IO extends Country("IO", "British Indian Ocean Territory")
  case AR extends Country("AR", "Argentina")
  case SV extends Country("SV", "El Salvador")
  case CX extends Country("CX", "Christmas Island")
  case MX extends Country("MX", "Mexico")
  case SI extends Country("SI", "Slovenia")
  case MT extends Country("MT", "Malta")
  case TW extends Country("TW", "Taiwan")
  case IR extends Country("IR", "Iran")
  case NI extends Country("NI", "Nicaragua")
  case MM extends Country("MM", "Myanmar")
  case GE extends Country("GE", "Georgia")
  case MV extends Country("MV", "Maldives")
  case LK extends Country("LK", "Sri Lanka")
  case PE extends Country("PE", "Peru")
  case CC extends Country("CC", "Cocos (Keeling) Islands")
  case BJ extends Country("BJ", "Benin")
  case BY extends Country("BY", "Belarus")
  case IS extends Country("IS", "Iceland")
  case SX extends Country("SX", "Sint Maarten")
  case GT extends Country("GT", "Guatemala")
  case MU extends Country("MU", "Mauritius")
  case SA extends Country("SA", "Saudi Arabia")
  case CG extends Country("CG", "Congo (Brazzaville)")
  case TC extends Country("TC", "Turks & Caicos Islands")
  case KW extends Country("KW", "Kuwait")
  case EG extends Country("EG", "Egypt")
  case FO extends Country("FO", "Faroe Islands")
  case RS extends Country("RS", "Serbia")
  case MN extends Country("MN", "Mongolia")
  case SR extends Country("SR", "Suriname")
  case CA extends Country("CA", "Canada")
  case UA extends Country("UA", "Ukraine")
  case NZ extends Country("NZ", "New Zealand")
  case JM extends Country("JM", "Jamaica")
  case LY extends Country("LY", "Libya")
  case TK extends Country("TK", "Tokelau")
  case GF extends Country("GF", "French Guiana")
  case SK extends Country("SK", "Slovakia")
  case TN extends Country("TN", "Tunisia")
  case DJ extends Country("DJ", "Djibouti")
  case SL extends Country("SL", "Sierra Leone")
  case GB extends Country("GB", "United Kingdom")
  case CV extends Country("CV", "Cape Verde Islands")
  case AS extends Country("AS", "American Samoa")
  case PY extends Country("PY", "Paraguay")
  case CZ extends Country("CZ", "Czech Republic")
  case CR extends Country("CR", "Costa Rica")
  case SC extends Country("SC", "Seychelles")
  case PM extends Country("PM", "Saint Pierre & Miquelon")
  case IN extends Country("IN", "India")
  case BZ extends Country("BZ", "Belize")
  case SM extends Country("SM", "San Marino")
  case AL extends Country("AL", "Albania")
  case FI extends Country("FI", "Finland")
  case VA extends Country("VA", "Holy See")
  case IL extends Country("IL", "Israel")
  case RE extends Country("RE", "Réunion")
  case GQ extends Country("GQ", "Equatorial Guinea")
  case ZA extends Country("ZA", "South Africa")
  case GP extends Country("GP", "Guadeloupe")
  case LT extends Country("LT", "Lithuania")
  case AU extends Country("AU", "Australia")
  case BB extends Country("BB", "Barbados")
  case SN extends Country("SN", "Senegal")
  case KE extends Country("KE", "Kenya")
  case YE extends Country("YE", "Yemen")
  case LR extends Country("LR", "Liberia")
  case GG extends Country("GG", "Guernsey")
  case SE extends Country("SE", "Sweden")
  case BR extends Country("BR", "Brazil")
  case BH extends Country("BH", "Bahrain")
  case MK extends Country("MK", "Macedonia")
  case CW extends Country("CW", "Curaçao")
  case AT extends Country("AT", "Austria")
  case GH extends Country("GH", "Ghana")
  case BL extends Country("BL", "Saint Barthélemy")
  case BN extends Country("BN", "Brunei Darussalam")
  case NC extends Country("NC", "New Caledonia")
  case HK extends Country("HK", "Hong Kong")
  case MA extends Country("MA", "Morocco")
  case CU extends Country("CU", "Cuba")
  case LV extends Country("LV", "Latvia")
  case EC extends Country("EC", "Ecuador")
  case GL extends Country("GL", "Greenland")
  case KZ extends Country("KZ", "Kazakhstan")
  case ZM extends Country("ZM", "Zambia")
  case ML extends Country("ML", "Mali")
  case HM extends Country("HM", "Heard Island and McDonald Islands")
  case EH extends Country("EH", "Western Sahara")
  case CM extends Country("CM", "Cameroon")
  case PW extends Country("PW", "Palau")
  case BW extends Country("BW", "Botswana")
  case GM extends Country("GM", "Gambia")
  case VN extends Country("VN", "Vietnam")
  case UY extends Country("UY", "Uruguay")
  case BV extends Country("BV", "Bouvet Island")
  case BI extends Country("BI", "Burundi")
  case NU extends Country("NU", "Niue")
  case CK extends Country("CK", "Cook Islands")
  case BM extends Country("BM", "Bermuda")
  case WF extends Country("WF", "Wallis & Futuna")
  case PA extends Country("PA", "Panama")
  case TT extends Country("TT", "Trinidad & Tobago")
  case GW extends Country("GW", "Guinea-Bissau")
  case SG extends Country("SG", "Singapore")
  case MW extends Country("MW", "Malawi")
  case IT extends Country("IT", "Italy")
  case MD extends Country("MD", "Moldova")
  case IE extends Country("IE", "Ireland")
  case ZW extends Country("ZW", "Zimbabwe")
  case BO extends Country("BO", "Bolivia")
  case MO extends Country("MO", "Macau")
  case HN extends Country("HN", "Honduras")
  case BG extends Country("BG", "Bulgaria")
  case NO extends Country("NO", "Norway")
  case PK extends Country("PK", "Pakistan")
  case SZ extends Country("SZ", "Swaziland")
  case FR extends Country("FR", "France")
  case CL extends Country("CL", "Chile")
  case ID extends Country("ID", "Indonesia")
  case TJ extends Country("TJ", "Tajikistan")
  case AG extends Country("AG", "Antigua & Barbuda")
  case TD extends Country("TD", "Chad")
  case ME extends Country("ME", "Montenegro")
  case PG extends Country("PG", "Papua New Guinea")
  case KN extends Country("KN", "Saint Christopher & Nevis")
  case IM extends Country("IM", "Isle of Man")
  case TV extends Country("TV", "Tuvalu")
  case ET extends Country("ET", "Ethiopia")
  case SD extends Country("SD", "Sudan")
  case NR extends Country("NR", "Nauru")
  case TO extends Country("TO", "Tonga")
  case NL extends Country("NL", "Netherlands")
  case UG extends Country("UG", "Uganda")
  case TF extends Country("TF", "French Southern Territories")
  case MR extends Country("MR", "Mauritania")
  case DO extends Country("DO", "Dominican Republic")
  case KG extends Country("KG", "Kyrgyzstan")
  case MF extends Country("MF", "Saint Martin")
  case MH extends Country("MH", "Marshall Islands")
  case SB extends Country("SB", "Solomon Islands")
  case MY extends Country("MY", "Malaysia")
  case MZ extends Country("MZ", "Mozambique")
  case TR extends Country("TR", "Turkey")
  case GU extends Country("GU", "Guam")
  case TZ extends Country("TZ", "Tanzania")
  case CH extends Country("CH", "Switzerland")
  case AE extends Country("AE", "United Arab Emirates")
  case GS extends Country("GS", "South Georgia & The South Sandwich Islands")
  case PS extends Country("PS", "Palestinian Territories")
  case KM extends Country("KM", "Comoros")
  case BF extends Country("BF", "Burkina Faso")
  case GY extends Country("GY", "Guyana")
  case CF extends Country("CF", "Central African Republic")
  case LS extends Country("LS", "Lesotho")
  case CY extends Country("CY", "Cyprus")
  case AW extends Country("AW", "Aruba")
  case NP extends Country("NP", "Nepal")
  case DE extends Country("DE", "Germany")
  case AQ extends Country("AQ", "Antarctica")
  case AM extends Country("AM", "Armenia")
  case FJ extends Country("FJ", "Fiji")
  case LC extends Country("LC", "Saint Lucia")
  case CI extends Country("CI", "Ivory Coast")
  case TM extends Country("TM", "Turkmenistan")
  case KY extends Country("KY", "Cayman Islands")
  case BD extends Country("BD", "Bangladesh")
  case CO extends Country("CO", "Colombia")
  case PF extends Country("PF", "French Polynesia")
  case KP extends Country("KP", "North Korea")
  case BS extends Country("BS", "Bahamas")
  case PT extends Country("PT", "Portugal")
  case GN extends Country("GN", "Guinea")
  case CD extends Country("CD", "Congo (Kinshasa)")
  case HU extends Country("HU", "Hungary")
}

object Country {
  private val countriesByName: Map[String, Country] = Country.values.map(c => c.name -> c).toMap

  def getCountryByName(name: String): Option[Country] = countriesByName.get(name)

  def getCountryByCode(code: String): Option[Country] = Try(Country.valueOf(code)).toOption

}
