#!/usr/bin/env bash

# Fail on any error
set -e

# Build Cloudformation template
(
  cd cdk
  yarn install --frozen-lockfile
  yarn lint
  yarn format:check
  yarn test
  yarn synth
)

# Verify database migrations are correct
./db/test.sh