name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    permissions:
      # Required by actions/checkout
      contents: read
      # Required by guardian/actions-riff-raff
      id-token: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      # Node is needed for CDK
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: yarn
          cache-dependency-path: cdk/yarn.lock

      # SBT is needed for the Scala Play app
      - uses: guardian/setup-scala@v1

      # Build CDK and Play (in sequence)
      - run: scripts/ci

      # Upload our build artifacts to S3
      - uses: guardian/actions-riff-raff@v4
        with:
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: identity:gatehouse
          configPath: cdk/cdk.out/riff-raff.yaml
          contentDirectories: |
            cdk.out:
              - cdk/cdk.out
            gatehouse:
              - target/gatehouse.deb
