name: Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      ORG: guardian-identity
      NODE_VERSION_FILE: cdk/.nvmrc
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
